spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/testdb
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true